### ISSUE TITLE
Unable to find the Auth facade

### ISSUE THREAD

**Issue by eaarranz** [rebing/timber-laravel#3]
I was trying to use your package but I'm unable to get it working. As soon as I try to use It as a logging channel it throws this exception:

`Call to undefined method Illuminate\Support\Facades\Auth::check()`

The full trace is this:
```
Uncaught Error: Call to undefined method Illuminate\Support\Facades\Auth::check() in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
Stack trace:
#0 /var/www/html/vendor/rebing/timber-laravel/src/Requests/Contexts/UserContext.php(17): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#1 /var/www/html/vendor/rebing/timber-laravel/src/Requests/Events/AbstractEvent.php(74): Rebing\Timber\Requests\Contexts\UserContext->getData()
#2 /var/www/html/vendor/rebing/timber-laravel/src/Requests/Events/CustomEvent.php(62): Rebing\Timber\Requests\Events\AbstractEvent->getContext()
#3 /var/www/html/vendor/rebing/timber-laravel/src/Requests/Events/AbstractEvent.php(30): Rebing\Timber\Requests\Events\CustomEvent->getContext()
#4 /var/www/html/vendor/rebing/timber-laravel/src/Requests/Events/AbstractEvent.php(43): Rebing\Timber\Requests\Events\AbstractEvent->send(true)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(157): Rebing\Timber\Requests\Even
```

Any ideas? I'll try to figure it out.

**Comment by eaarranz** [comment]
I found it, silly me... We are using Sentinel instead of the default Auth system.
